version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging into Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 596451156793.dkr.ecr.us-east-1.amazonaws.com

  build:
    commands:
      - echo Building Docker image...
      - docker build -t brain-tasks-app .

      - echo Tagging Docker image...
      - docker tag brain-tasks-app:latest 596451156793.dkr.ecr.us-east-1.amazonaws.com/brain-tasks-app:v1

  post_build:
    commands:
      - echo Pushing image to ECR...
      - docker push 596451156793.dkr.ecr.us-east-1.amazonaws.com/brain-tasks-app:v1

      - echo Updating kubeconfig...
      - aws eks update-kubeconfig --region us-east-1 --name brain-tasks-eks

      - echo Deploying application...
      - kubectl apply -f deployment.yaml
      - kubectl apply -f service.yaml

      - kubectl rollout status deployment/brain-tasks-app

artifacts:
  files:
    - '**/*'
